version: '2'
services:
  web_1:
    image: whitebox/xls2txt:alpine-0.1.0
    command: bundle exec thin start -p 9595
    environment:
      - RACK_ENV=production
    volumes:
      - /app/public
  nginx_1:
    image: whitebox/nginx:alpine-0.1.0
    restart: always
    links:
      - web_1:web_1
    ports:
      - 80:80
    volumes_from:
      - web_1
    volumes:
      - /app/public
